### ISSUE TITLE
Feature request - Current Print LAyer

### ISSUE THREAD

**Issue by pmbroth** [QIDITECH/QIDI_MAX3#21]
Is it possible that on the printer., when printing, it displays current layer being printed, and total layers.   Example  Curerent Layer 23  Total Layers 600.   I have had this on other printers, and it was useful.

Thank you

Brian

**Comment by QIDITECH** [comment]
Ok, we will consider your suggestion if there is enough space on the display.

**Comment by pmbroth** [comment]
can be as simple as      Layer 23/450

**Comment by CChen616** [comment]
The latest version of fluidd now includes built-in functionality to display the current layer and total layers. For instance, my version of fluidd is as follows:
```
fluidd: v1.19.0-6184c739
```
And the print status looks like

![image](https://github.com/QIDITECH/QIDI_PLUS3/assets/88018764/b8e1c9ce-0896-4a7d-9137-0b5292455b15)

Regarding support for printer screens, due to the need to upgrade moonraker and considerations for the stability of older models, it may take a long time to test. But this feature will be incorporated into our next-generation machines.

**Comment by Fisheye3D** [comment]
Why not release a guide on how to update the mcu on the printhead to the latest klipper so everyone can use updated functionality,  this next generation reasoning makes no sense when it's software and easily updated.

**Comment by CChen616** [comment]
The printhead board we currently use is not on the list of boards supported by Klipper for firmware updates via command line. It requires disassembly and connection to another device for updating. If some users opt not to update the firmware while others do, it becomes challenging to maintain update packages for both versions simultaneously.

**Comment by Fisheye3D** [comment]
I'm confused, It doesn't need a connection to another device, You can hit the boot button on the device and it mounts to the mkspi as a drive, you can then copy over the klipper.uf2 over to the mounted drive. Then it's updated.

**Comment by CChen616** [comment]
Apologies for the confusion, but updating Klipper overwrites many Klipper files, resulting in the loss of our modifications to Klipper. Even after resolving these conflicts, due to some users not wanting to go through the hassle of updating MCU firmware for Klipper, we need to maintain two versions of the update package. Given our current update methods, this will be a significant amount of work.

**Comment by pmbroth** [comment]
Yes, I know Fluid has that, but I do not always have the computer on.  Also, so this means we will never be able to upgrade to a new kliiper/moonraker version?  That is really poor design if that is true.
