### ISSUE TITLE
beste einstellung ABS+

### ISSUE THREAD

**Issue by Anelke** [QIDITECH/QIDI_MAX3#34]
Habe schon viel probiert  , aber immer noch spannungsrisse!!!

**Comment by CChen616** [comment]
Your question is quite brief, which makes it difficult to pinpoint the exact issue. If you are referring to the settings in the slicing software when printing with ABS+ filament, please provide the details of your settings during the print. If the issue lies elsewhere, please describe your problem in more detail so that I can provide a more accurate response.
