### ISSUE TITLE
No Z lift from purge line to the startpoint of the print. If I use the travel lift and lift hight results in a crash

### ISSUE THREAD

**Issue by Stoneprophet** [QIDITECH/QIDI_MAX3#44]
Hello,

I have encountered the following problem. I would like to print a label in 2 colors. The first color is printed and then the rest of the object is printed over it. This works perfectly.

The problem is that the print head ignores or ignores the lift height from the end of the purge line to the start point of the print and thus collides with what has already been printed.

I don't think this is intended. The first lift to the specified lift height must take place directly after the purge line. At the moment the print head moves with the distance of the first layer height (0.2mm) to the starting point as far as I can see.

Regards Alex

**Comment by Stoneprophet** [comment]
I changed the G-code by myself. Now it works, but you have to know about that bug and other people can't do changes in G-code.
To find out that "lift height" do not work probably, it needs a crash first. Otherwise you will not notice that.

**Comment by CChen616** [comment]
It's challenging to provide a detailed analysis without understanding your specific process. 

In QIDISlicer version 1.1.2, when you click on `Preview` and then select a specific height, clicking the `+` symbol on the height line will automatically insert the `Color Change G-code` set in the `Custom G-code` section, which defaults to the M0 pause G-code for easy filament change.
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/88018764/14fa2847-ae3e-456e-8d6d-10e6c4d979d6)
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/88018764/86388490-7937-4adf-9eb4-fb998b5b4d29)
From your description, it seems you might be experiencing issues with multi-color printing due to using a different method. Please provide more details about your process, the slicing software, and the version you're using.

**Comment by Stoneprophet** [comment]
No it is no multi color printing as intended. My used Technique works till 1mm height without problems. Higher I didn't test.

I made some pictures with explanations. I hope that will help you to understand how I do that.

Here is a video from the technique. I copy that to the QIDI Slicer. 

[![Video](https://img.youtube.com/vi/0Sla-vIsvh4/0.jpg)](https://www.youtube.com/watch?v=0Sla-vIsvh4)


![1 qidi-slicer_AKqFoNqQ6s](https://github.com/QIDITECH/QIDI_MAX3/assets/158781146/368f8354-b47c-4dff-a757-5c7d5d66611c)
![2 qidi-slicer_jlRgTxbMWB](https://github.com/QIDITECH/QIDI_MAX3/assets/158781146/3e5ce26c-ecb1-47cf-ab7e-54de0393d261)
![3 qidi-slicer_MItJvwOPbO](https://github.com/QIDITECH/QIDI_MAX3/assets/158781146/eb2fe3d6-ff06-4c8d-ab04-564eea172088)
![4 qidi-slicer_IpvFqPqtZe](https://github.com/QIDITECH/QIDI_MAX3/assets/158781146/4a301829-dfc4-424b-82a4-351e00f45ef8)
![5 PXL_20240329_105143109](https://github.com/QIDITECH/QIDI_MAX3/assets/158781146/7136b97a-4288-4a7d-8393-51a92f55fb94)
![6 qidi-slicer_6x6Z0P0mRx](https://github.com/QIDITECH/QIDI_MAX3/assets/158781146/3eb5dd7e-865d-4b84-b3e0-3844d97acb83)

**Comment by QIDITECH** [comment]
Thanks for your feedback, we will fix this problem in the next version of the QIDISlicer.

**Comment by Stoneprophet** [comment]
I tested it by chance yesterday with the new version and it now works perfectly without any changes. Thank you, that's how I imagine good support.
